export default {
	LOG_IN_SUCCESS:"LOG_IN_SUCCESS",
	LOG_OUT:"LOG_OUT",
	LOG_IN_FAILED:"LOG_IN_FAILED",
	AUTHENTICATING:"AUTHENTICATING",
	FETCHINGLOGIN_DETAILS:"FETCHINGLOGIN_DETAILS",
	SEARCH_INPUT_KEYWORD:"SEARCH_INPUT_KEYWORD",
	ALL_PLANETS:"ALL_PLANETS",
};
